apiVersion: v1
kind: Service
metadata:
  name: demorestspringboot-v1
spec:
  selector:
    app: demorestspringboot-v1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort